#pragma once

#include <Arduino.h>

namespace HardwareConfig {

// WS2812B identification LED: LED 7 is magenta, all others stay off.
constexpr uint8_t RGB_PIN = 15;
constexpr uint8_t RGB_LED_COUNT = 8;
constexpr uint8_t IDENTIFICATION_LED_INDEX = 6;  // LED 7, zero-based
constexpr uint8_t IDENTIFICATION_LED_BRIGHTNESS = 40;

// MPU6050 / GY-521
constexpr uint8_t I2C_SDA_PIN = 21;
constexpr uint8_t I2C_SCL_PIN = 22;
constexpr uint8_t MPU6050_ADDRESS = 0x68;

// TB6612FNG. Driver channel A is connected to M2 (left), channel B to M1 (right).
constexpr uint8_t LEFT_PWM_PIN = 4;    // PWA -> M2
constexpr uint8_t LEFT_DIR_PIN = 16;   // AIN1; AIN2 is generated by U23
constexpr uint8_t RIGHT_PWM_PIN = 18;  // PWB -> M1
constexpr uint8_t RIGHT_DIR_PIN = 23;  // BIN1; BIN2 is generated by U23
constexpr uint8_t MOTOR_STANDBY_PIN = 17;

constexpr uint8_t LEFT_PWM_CHANNEL = 0;
constexpr uint8_t RIGHT_PWM_CHANNEL = 1;
constexpr uint32_t MOTOR_PWM_FREQUENCY_HZ = 20000;
constexpr uint8_t MOTOR_PWM_RESOLUTION_BITS = 8;

// Quadrature encoders. M2 is the left wheel, M1 is the right wheel.
constexpr uint8_t LEFT_ENCODER_A_PIN = 19;   // M2A
constexpr uint8_t LEFT_ENCODER_B_PIN = 25;   // M2B
constexpr uint8_t RIGHT_ENCODER_A_PIN = 27;  // M1A
constexpr uint8_t RIGHT_ENCODER_B_PIN = 26;  // M1B

}  // namespace HardwareConfig
